name: release

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v6
        with:
          submodules: recursive
      - name: Setup execution flag for gradlew
        run: chmod +x native.sh
      - name: Obtain solution name for folders/URL from repository name
        run: |
          SOLUTION_NAME=${GITHUB_REPOSITORY#*/}
          echo "Solution name: $SOLUTION_NAME"
          echo "SOLUTION_NAME=$SOLUTION_NAME" >> "$GITHUB_ENV"
      - name: Build with Gradle
        env:
          PROTECTED_PROPERTIES_PATH: /media/myusb/default
        run: ./native.sh --skip-deps
      - name: Read version from version.properties
        run: |
          VERSION_NAME=`grep '^version =' Cargo.toml | head -1 | cut -d'"' -f2`
          echo "Version to be published: $VERSION_NAME"
          echo "VERSION_NAME=$VERSION_NAME" >> "$GITHUB_ENV"
      - name: Publish artifact
        run: |
          rm -rf "/media/store/release/$SOLUTION_NAME/$VERSION_NAME"
          mkdir -p "/media/store/release/$SOLUTION_NAME/$VERSION_NAME/jniLibs"
          mkdir -p "/media/store/release/$SOLUTION_NAME/$VERSION_NAME/protos"
          cp -a ./flutter/android/app/src/main/jniLibs/. /media/store/release/$SOLUTION_NAME/$VERSION_NAME/jniLibs/
          cp -a ./libs/hbb_common/protos/. /media/store/release/$SOLUTION_NAME/$VERSION_NAME/protos/
          echo "[native deps dir](http://builder.tmgltd.co.il/$SOLUTION_NAME/$VERSION_NAME)" >> $GITHUB_STEP_SUMMARY
      - name: Add release tag to sources
        run: |
          git config user.name builder
          git config user.email build@tmgltd.co.il
          git tag $VERSION_NAME -a -m "$VERSION_NAME released"
          git push origin $VERSION_NAME
